spring:
  application:
    name: eureka-consumer

server:
  port: 8003

# eureka-provider acts as a service to call here
eureka-provider:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 15000